/*

 SPRITES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char sprites[] =
{
  0x00,0x00,0x00,0x00,0x00,0x00,0x1F,0x1F,
  0x18,0x18,0x14,0x14,0x12,0x12,0x11,0x11
};

/* End of SPRITES.C */
